### ISSUE TITLE
As a user, I can add contacts

### ISSUE THREAD

**Issue by tanshiyu1999** [AY2324S1-CS2103T-W08-3/tp#12]
...so that I can keep track of new recruiters and organizations easily.

### High Priority
- [x] As a user, I can add organizations’ with their name.
- [x] As a user, I can add a contact number for an organization.
- [x] As a user, I can add a URL for an organization.
- [x] As a user, I can include my application status with an organization.
- [x] As a user, I can include my target job application role with an organization.
- [ ] As a user, I can add recruiters’ with their name.
- [ ] As a user, I can add a contact number for a recruiter.
- [ ] As a user, I can add a URL for a recruiter.
- [ ] As a user, I can link a recruiter with an organization they are affiliated with so that I can note the relevant people that are involved with the company.
---
### Low Priority
- [ ] As a user, I can add other contact details to the organization’s information.
- [ ] As a user, I can add other contact details to the recruiter’s information.
