### ISSUE TITLE
As a user, I can delete contacts

### ISSUE THREAD

**Issue by tanshiyu1999** [AY2324S1-CS2103T-W08-3/tp#13]
...so that I can avoid cluttering my list with unused contacts.

### High Priority
- [X] As a user, I can delete contacts (organizations or recruiters) by their index in the list.
- [x] As a user, I can delete organizations by their ID.
- [x] As a user, I can bulk delete my recruiters when I delete an organization.
