### ISSUE TITLE
As a user, I can view my contacts

### ISSUE THREAD

**Issue by tanshiyu1999** [AY2324S1-CS2103T-W08-3/tp#14]
...so that I can see the recruiters and organizations I added in the database.

### High Priority
- [ ] As a user, I can see the list of organizations I am aiming for.
- [ ] As a user, I can see the list of recruiters I have added in my list.
- [x] As a user, I can see the list of both organizations and recruiters.
