### ISSUE TITLE
As a user, I can type shorter arguments and known values with auto-completion

### ISSUE THREAD

**Issue by wxwern** [AY2324S1-CS2103T-W08-3/tp#64]
...so that I can type my command more quickly and efficiently.

### Medium Priority
- [ ] As a user, I can type a prefix of an argument and they will be auto-substituted with the full form and accepted as I complete the command.
- [ ] As a user, I can auto-complete arguments by pressing `TAB`.
- [ ] As a user, I can auto-complete values with known presets or values by pressing `TAB`.
- [ ] As a user, I can be warned when an argument prefix is ambiguous and choose which one I mean, so that I don’t need to look up the documentation to find out.

### Low Priority
- [ ] As a user, I can be hinted if an argument does not match anything but has a very close match due to a typo, so that I do not need to retype the entire argument or command.
