### ISSUE TITLE
As a user, I can track my job applications

### ISSUE THREAD

**Issue by CJ-Lee01** [AY2324S1-CS2103T-W08-3/tp#66]
- [ ] As a user, I can find job applications whose details contain a specific keyword/phrase.
- [ ] As a user, I can sort my job applications by their date in ascending/descending order.
- [X] ~~As a user, I can sort my job applications by other tags (such as quoted salary, job type), so that I can quickly see which jobs I may prefer.~~ (removed)
- [ ] As a user, I can see that my job applications which are stagnant for too long are highlighted.

**Comment by CJ-Lee01** [comment]
Removed sorting by other tags as they will require more time to implement

**Comment by CJ-Lee01** [comment]
Not done yet

**Comment by CJ-Lee01** [comment]
Closed as it is too tedious to complete within 1.3
