### ISSUE TITLE
As a user, I can sort contacts

### ISSUE THREAD

**Issue by wamps-jp** [AY2324S1-CS2103T-W08-3/tp#75]
...so that I can arrange my list depending on my needs.

#### High Priority

- [x] As a user, I can sort contacts (organizations or recruiters) by their name.
- [x] As a user, I can sort contacts (organizations or recruiters) by their id.
- [x] As a user, I can sort contacts (organizations or recruiters) by their address.
- [x] As a user, I can sort contacts (organizations or recruiters) by their url.
- [x] As a user, I can sort contacts (organizations or recruiters) by their phone.
- [x] As a user, I can sort contacts (organizations or recruiters) by their email.

**Comment by McNaBry** [comment]
Closed by #72
